package jp.leopanda.gPlusAnalytics.client.enums;

/**
 * アイテムデータのフィルタ種類
 * 
 * @author LeoPanda
 *
 */
public enum FilterType {
  ACTIVITY_TABLE_PLUSONER, ACTIVITIES_KEYWORD, ACTIVITIES_PUBLISHED_YEAR,
  ACTIVITIES_PUBLISHED_MONTH, ACTIVITIES_ACCESSDESCRIPTION, PLUSONER_NUMOFPLUSONE,
  PLUSONER_TABLE_ACTIVITY, PLUSONER_KEYWORD, 
  RESET_ITEMS;
}
