package jp.leopanda.gPlusAnalytics.client.enums;

/**
 * アイテムデータのフィルタ種類
 * 
 * @author LeoPanda
 *
 */
public enum FilterType {
  ACTIVITIES_BY_PLUSONER, ACTIVITIES_BY_KEYWORD, ACTIVITIES_BY_PUBLISHED_YEAR,
  ACTIVITIES_BY_PUBLISHED_MONTH, ACTIVITIES_BY_ACCESSDESCRIPTION, PLUSONERS_BY_NUMOFPLUSONE,
  ACTIVITIES_BY_NUMOFPLUSONE,PLUSONERS_BY_ACTIVITY, PLUSONERS_BY_KEYWORD,
  RESET_ITEMS;
}
